package com.estudo.blog.utils;

import com.estudo.blog.model.Post;
import com.estudo.blog.repository.CodeBlogRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Component
public class DummyData {

    @Autowired
    CodeBlogRepository codeBlogRepository;

    //@PostConstruct
    public void savePosts() {
        List<Post> postList = new ArrayList<>();
        Post post1 = new Post();
        post1.setAutor("A");
        post1.setTitulo("Primeiro");
        post1.setData(LocalDate.now());
        post1.setTexto("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae dapibus orci. Pellentesque gravida odio arcu, eget porta nunc tincidunt eget. Sed et sollicitudin risus. Pellentesque tempus quam non lacus vestibulum iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam accumsan ipsum id pellentesque vulputate. Nulla at libero at enim venenatis efficitur in non eros. Proin molestie quam nec nunc rhoncus ultricies. Sed lacinia vel justo sed ullamcorper. Fusce tristique venenatis nulla ut hendrerit.\n" +
                "\n" +
                "Sed id dictum mi. Aliquam erat volutpat. Mauris blandit et purus non euismod. Donec aliquam vitae nunc ac euismod. Fusce sollicitudin arcu efficitur aliquet vulputate. Curabitur et mauris ullamcorper, viverra eros vitae, mollis orci. Vivamus vulputate nec est et facilisis. Etiam ex ligula, pharetra ac pharetra a, venenatis sit amet velit.\n" +
                "\n" +
                "Quisque erat neque, ullamcorper id pulvinar eu, pellentesque sit amet nunc. Sed est purus, eleifend non maximus fringilla, convallis quis tortor. Cras non consectetur tellus. Proin pellentesque a mi aliquam tempor. Quisque venenatis libero eu leo porttitor pharetra. Integer fringilla, lorem facilisis sodales suscipit, neque nibh mattis sem, aliquam blandit tellus risus at sapien. Proin turpis libero, aliquet at neque sed, dapibus maximus erat. Proin tempus lacinia neque, ut sollicitudin ligula efficitur ac. Vestibulum lobortis elementum neque pretium vestibulum.\n" +
                "\n" +
                "Nam suscipit nibh vel orci eleifend, id finibus urna tempor. Cras vitae faucibus erat, ut pulvinar metus. Praesent dignissim ante vel mauris commodo cursus. Aliquam ac massa quis tellus eleifend aliquam. Duis elementum non metus ut lacinia. Donec rhoncus, tortor sit amet congue aliquam, felis elit mattis erat, vel ultrices lectus nibh a ante. Morbi eu faucibus risus, pharetra aliquet est. Sed accumsan consequat leo, et pretium nisl volutpat id. Aliquam quis magna non purus lobortis dignissim.\n" +
                "\n" +
                "Quisque dapibus lorem metus, sed sagittis orci feugiat quis. Integer interdum eros non eros tempus cursus. Mauris nulla diam, eleifend quis molestie quis, mollis tristique elit. Quisque id sapien quis est accumsan ornare in non lacus. Integer varius tellus non leo imperdiet posuere. Nunc efficitur augue massa, sed cursus erat consectetur eu. Etiam leo dolor, dictum in vestibulum non, lobortis vel lectus. Donec ut justo in arcu porttitor auctor. Maecenas urna ipsum, tristique vel suscipit consequat, pharetra a velit. Sed in ullamcorper leo, non cursus nisl. Aenean et varius turpis. Morbi gravida neque ex, sit amet facilisis turpis vestibulum vestibulum. Phasellus et bibendum lacus, ac dictum turpis.\n" +
                "\n" +
                "Phasellus scelerisque posuere volutpat. Proin volutpat velit sed turpis pulvinar, ut sollicitudin diam convallis. Ut fringilla elit ut nisi ultricies, nec semper leo posuere. Mauris sagittis velit felis, vitae lacinia mi dapibus sed. Vestibulum posuere accumsan ex, quis euismod tortor laoreet at. Nullam non nisi in eros accumsan ullamcorper et vitae neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam posuere metus sed odio rutrum, non commodo elit vulputate. Integer eget scelerisque turpis.\n" +
                "\n" +
                "Phasellus tincidunt lobortis mi, ut porttitor libero consectetur nec. Proin quis orci quis odio condimentum feugiat sit amet non dolor. Phasellus molestie dui quis leo malesuada ultricies. Praesent est est, vehicula id euismod in, vehicula at felis. Pellentesque sit amet elit vel urna tristique rutrum ac id urna. Nunc nec tortor quam. Duis sapien dui, gravida et elit eu, sagittis luctus enim. Mauris accumsan vel est non gravida. Vestibulum porttitor tellus libero, in aliquet est faucibus eget. Duis bibendum, tellus et eleifend congue, sem libero aliquam enim, vel viverra lorem risus vel leo. Pellentesque fringilla vulputate dignissim. Nullam tempor, justo sed interdum feugiat, enim ante vulputate metus, vel sodales diam magna nec ex.\n" +
                "\n" +
                "Maecenas ut sollicitudin quam. Morbi suscipit arcu ut lacus congue dapibus. Aliquam varius ex in sapien efficitur semper. Nulla condimentum, libero sed aliquet sodales, eros sapien interdum ipsum, et venenatis libero risus id velit. Vestibulum non imperdiet neque, semper semper mi. Aenean lobortis purus est, eu egestas quam dignissim et. Aliquam erat volutpat. Cras gravida eget nibh lacinia mollis. Ut facilisis lectus eu tortor aliquam, a tempus velit posuere. Proin lobortis risus vel turpis lacinia ultrices. Aliquam erat volutpat. Ut sit amet vestibulum dolor.\n" +
                "\n" +
                "Cras at velit vitae erat tempor finibus. Nullam arcu purus, consectetur in sapien sed, vulputate interdum nisi. Etiam egestas at nisl eu tempus. Curabitur pretium aliquam urna, sed pulvinar nulla rutrum a. Donec non risus non ante vestibulum interdum. Curabitur dignissim, sem ut egestas lacinia, nisi ante varius odio, in fermentum risus ex ut sem. Cras sit amet est pharetra, hendrerit odio id, placerat dui. Curabitur vehicula, est vel porta consectetur, elit metus suscipit tellus, vitae feugiat felis justo vitae magna. Nam tempor hendrerit ligula ac hendrerit. Aliquam erat volutpat. In sed facilisis magna. Mauris et porttitor arcu, eget gravida dolor.\n" +
                "\n" +
                "Mauris a nulla nibh. Cras tristique in ante et lobortis. Ut pretium est metus, nec feugiat massa consectetur eget. Praesent interdum dignissim nunc a efficitur. Nunc malesuada accumsan nibh nec consectetur. Etiam vitae ex dapibus, sodales tortor eu, euismod odio. Nullam commodo blandit elit, pellentesque tristique ipsum cursus eu. Suspendisse eu scelerisque nunc, nec blandit nisl. Suspendisse eleifend condimentum porttitor. Proin efficitur tempor urna, eget volutpat augue ultrices eu. In molestie ipsum cursus ligula commodo pretium. Fusce convallis tellus id libero dapibus scelerisque. Fusce sit amet lorem consectetur, tristique erat eu, blandit neque. Duis nunc est, tincidunt ac feugiat vel, facilisis sit amet sapien.\n" +
                "\n" +
                "Aenean erat tortor, volutpat vel lectus nec, feugiat lobortis dui. Nullam varius mauris eget facilisis lacinia. Phasellus mollis ligula mauris, sit amet auctor nisi consectetur dapibus. Mauris justo diam, vehicula at justo non, placerat tempor diam. Aliquam erat volutpat. Aliquam nec mollis mauris, id ornare libero. Maecenas et dolor ullamcorper, rhoncus dui sed, sollicitudin augue.\n" +
                "\n" +
                "Pellentesque sit amet nisl elementum magna feugiat vestibulum. Aenean dapibus neque facilisis consectetur ornare. Cras tristique eu mauris at ornare. Cras massa est, maximus id fringilla sit amet, vehicula in massa. Sed mi mauris, vestibulum eget mi sit amet, malesuada eleifend massa. Aliquam porta elit ac arcu sodales, at fringilla sem varius. Duis consequat pulvinar est, eget malesuada leo posuere sit amet. Nullam egestas, sem eu dictum mollis, massa tortor pharetra lacus, id rhoncus sapien est ut velit.\n" +
                "\n" +
                "Aliquam viverra sem ac erat pellentesque, non gravida enim dictum. Donec a ornare eros. Nunc aliquet ultrices lectus, quis faucibus eros tempus et. Aliquam condimentum nisi et vehicula sollicitudin. Sed porttitor ligula enim, eget tincidunt eros pulvinar viverra. Aliquam pharetra mauris et elementum tincidunt. Pellentesque rutrum, ante in dictum mattis, lectus magna pellentesque dui, ac porttitor urna neque in dui.\n" +
                "\n" +
                "Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce euismod pharetra mauris et hendrerit. Phasellus purus nunc, fermentum in faucibus sit amet, laoreet sed ipsum. Sed volutpat diam a egestas congue. Donec dapibus laoreet dui sit amet suscipit. Donec ultrices erat congue malesuada ultrices. Ut eleifend orci at condimentum egestas. Nulla rutrum mauris fermentum ex efficitur varius. Etiam vel metus quis est dapibus tempus eu quis leo. Suspendisse sodales massa ac sem facilisis feugiat.\n" +
                "\n" +
                "Duis viverra vestibulum quam, et tristique tellus interdum id. Suspendisse potenti. Nam mattis dui ac lacus tincidunt, at sollicitudin elit vulputate. Vivamus porta ut urna eget imperdiet. Integer elementum fringilla arcu id porta. Curabitur molestie ex eget condimentum blandit. Donec ornare venenatis fringilla. Suspendisse mattis tellus pulvinar, facilisis enim quis, feugiat orci. Mauris augue lacus, sollicitudin sed vulputate ut, hendrerit et arcu. Nam ornare posuere congue. Proin sed tempus arcu, vel suscipit eros. Integer consequat posuere enim vel iaculis. Sed vel sodales magna. Aliquam erat volutpat. Etiam congue pellentesque nibh at eleifend.\n" +
                "\n" +
                "Phasellus lobortis dignissim urna, vel maximus erat bibendum a. Integer mi ligula, efficitur at pretium ut, auctor eget tellus. Ut pharetra, est ut dictum rhoncus, risus ante pellentesque velit, non rutrum est nisl nec neque. Quisque condimentum aliquet enim ac bibendum. Nullam vestibulum felis odio, in pretium odio mattis non. Etiam sed odio ut sem tempor faucibus. Phasellus ultrices nisi a lectus accumsan, vel malesuada velit luctus. Integer pellentesque congue risus, in semper nisl cursus eget. Sed aliquam ipsum felis.\n" +
                "\n" +
                "Pellentesque ultricies ex in posuere ullamcorper. Cras suscipit libero at felis dictum ultrices. In et maximus dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Aenean feugiat velit velit, ut ultrices metus auctor eget. Morbi in leo ante. Duis eget augue sit amet dolor pharetra porta. Ut non ipsum rhoncus est consectetur volutpat. Donec pharetra ultrices felis a venenatis. Nulla placerat consectetur mauris, id congue quam vehicula eget. Etiam accumsan malesuada orci non imperdiet.\n" +
                "\n" +
                "Fusce tincidunt mattis libero, quis lacinia tortor porttitor non. Sed interdum feugiat nisi, ac fermentum lectus rutrum ut. Mauris cursus aliquet volutpat. Pellentesque eu turpis iaculis elit hendrerit laoreet. Vestibulum cursus felis et risus tempus, vitae sagittis diam pellentesque. Vestibulum non tempor leo. Duis pretium felis tortor, sed commodo nisi suscipit sit amet. Nam pharetra, lectus ac tincidunt egestas, diam urna auctor purus, eu pharetra nulla mi et ipsum. Aliquam venenatis eros quis lorem pharetra semper. Sed non tortor diam. Duis egestas, dolor vitae consectetur facilisis, turpis dui rutrum neque, sit amet eleifend elit libero sed turpis. Duis pharetra neque et ipsum porta rhoncus.\n" +
                "\n" +
                "Mauris enim enim, gravida eu egestas sit amet, ultrices eu felis. Etiam semper faucibus dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu elit at lectus pretium sodales. Etiam malesuada lorem at tincidunt aliquet. Mauris in orci a leo sollicitudin auctor sit amet vitae felis.\n" +
                "\n" +
                "Nullam sit amet imperdiet ipsum, pharetra facilisis risus. Pellentesque sem felis, bibendum vel lacus id, mattis elementum velit. Sed eu ullamcorper nibh. Nunc pharetra augue molestie dui posuere pellentesque. Suspendisse maximus nunc vitae congue commodo. In hac habitasse platea dictumst. Nulla tempus fermentum mi, a fringilla magna gravida vel. Quisque a augue non tortor lobortis faucibus ut eu ligula. Fusce ullamcorper, magna ut mattis vestibulum, nunc urna mollis lorem, eget dapibus nibh arcu ut erat. Proin convallis rhoncus purus a mattis. Nulla mattis vel felis ut iaculis. Integer congue, massa ac faucibus volutpat, ante ipsum elementum diam, at porta diam quam non velit. Nunc at elementum neque, ut congue ipsum. In blandit tincidunt pellentesque. Fusce non enim eu tortor ultricies sagittis. Ut elementum eros sed lorem posuere egestas.");

        Post post2 = new Post();
        post2.setAutor("D");
        post2.setData(LocalDate.now());
        post2.setTitulo("Segundo");
        post2.setTexto("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae dapibus orci. Pellentesque gravida odio arcu, eget porta nunc tincidunt eget. Sed et sollicitudin risus. Pellentesque tempus quam non lacus vestibulum iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam accumsan ipsum id pellentesque vulputate. Nulla at libero at enim venenatis efficitur in non eros. Proin molestie quam nec nunc rhoncus ultricies. Sed lacinia vel justo sed ullamcorper. Fusce tristique venenatis nulla ut hendrerit.\n" +
                "\n" +
                "Sed id dictum mi. Aliquam erat volutpat. Mauris blandit et purus non euismod. Donec aliquam vitae nunc ac euismod. Fusce sollicitudin arcu efficitur aliquet vulputate. Curabitur et mauris ullamcorper, viverra eros vitae, mollis orci. Vivamus vulputate nec est et facilisis. Etiam ex ligula, pharetra ac pharetra a, venenatis sit amet velit.\n" +
                "\n" +
                "Quisque erat neque, ullamcorper id pulvinar eu, pellentesque sit amet nunc. Sed est purus, eleifend non maximus fringilla, convallis quis tortor. Cras non consectetur tellus. Proin pellentesque a mi aliquam tempor. Quisque venenatis libero eu leo porttitor pharetra. Integer fringilla, lorem facilisis sodales suscipit, neque nibh mattis sem, aliquam blandit tellus risus at sapien. Proin turpis libero, aliquet at neque sed, dapibus maximus erat. Proin tempus lacinia neque, ut sollicitudin ligula efficitur ac. Vestibulum lobortis elementum neque pretium vestibulum.\n" +
                "\n" +
                "Nam suscipit nibh vel orci eleifend, id finibus urna tempor. Cras vitae faucibus erat, ut pulvinar metus. Praesent dignissim ante vel mauris commodo cursus. Aliquam ac massa quis tellus eleifend aliquam. Duis elementum non metus ut lacinia. Donec rhoncus, tortor sit amet congue aliquam, felis elit mattis erat, vel ultrices lectus nibh a ante. Morbi eu faucibus risus, pharetra aliquet est. Sed accumsan consequat leo, et pretium nisl volutpat id. Aliquam quis magna non purus lobortis dignissim.\n" +
                "\n" +
                "Quisque dapibus lorem metus, sed sagittis orci feugiat quis. Integer interdum eros non eros tempus cursus. Mauris nulla diam, eleifend quis molestie quis, mollis tristique elit. Quisque id sapien quis est accumsan ornare in non lacus. Integer varius tellus non leo imperdiet posuere. Nunc efficitur augue massa, sed cursus erat consectetur eu. Etiam leo dolor, dictum in vestibulum non, lobortis vel lectus. Donec ut justo in arcu porttitor auctor. Maecenas urna ipsum, tristique vel suscipit consequat, pharetra a velit. Sed in ullamcorper leo, non cursus nisl. Aenean et varius turpis. Morbi gravida neque ex, sit amet facilisis turpis vestibulum vestibulum. Phasellus et bibendum lacus, ac dictum turpis.\n" +
                "\n" +
                "Phasellus scelerisque posuere volutpat. Proin volutpat velit sed turpis pulvinar, ut sollicitudin diam convallis. Ut fringilla elit ut nisi ultricies, nec semper leo posuere. Mauris sagittis velit felis, vitae lacinia mi dapibus sed. Vestibulum posuere accumsan ex, quis euismod tortor laoreet at. Nullam non nisi in eros accumsan ullamcorper et vitae neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam posuere metus sed odio rutrum, non commodo elit vulputate. Integer eget scelerisque turpis.\n" +
                "\n" +
                "Phasellus tincidunt lobortis mi, ut porttitor libero consectetur nec. Proin quis orci quis odio condimentum feugiat sit amet non dolor. Phasellus molestie dui quis leo malesuada ultricies. Praesent est est, vehicula id euismod in, vehicula at felis. Pellentesque sit amet elit vel urna tristique rutrum ac id urna. Nunc nec tortor quam. Duis sapien dui, gravida et elit eu, sagittis luctus enim. Mauris accumsan vel est non gravida. Vestibulum porttitor tellus libero, in aliquet est faucibus eget. Duis bibendum, tellus et eleifend congue, sem libero aliquam enim, vel viverra lorem risus vel leo. Pellentesque fringilla vulputate dignissim. Nullam tempor, justo sed interdum feugiat, enim ante vulputate metus, vel sodales diam magna nec ex.\n" +
                "\n" +
                "Maecenas ut sollicitudin quam. Morbi suscipit arcu ut lacus congue dapibus. Aliquam varius ex in sapien efficitur semper. Nulla condimentum, libero sed aliquet sodales, eros sapien interdum ipsum, et venenatis libero risus id velit. Vestibulum non imperdiet neque, semper semper mi. Aenean lobortis purus est, eu egestas quam dignissim et. Aliquam erat volutpat. Cras gravida eget nibh lacinia mollis. Ut facilisis lectus eu tortor aliquam, a tempus velit posuere. Proin lobortis risus vel turpis lacinia ultrices. Aliquam erat volutpat. Ut sit amet vestibulum dolor.\n" +
                "\n" +
                "Cras at velit vitae erat tempor finibus. Nullam arcu purus, consectetur in sapien sed, vulputate interdum nisi. Etiam egestas at nisl eu tempus. Curabitur pretium aliquam urna, sed pulvinar nulla rutrum a. Donec non risus non ante vestibulum interdum. Curabitur dignissim, sem ut egestas lacinia, nisi ante varius odio, in fermentum risus ex ut sem. Cras sit amet est pharetra, hendrerit odio id, placerat dui. Curabitur vehicula, est vel porta consectetur, elit metus suscipit tellus, vitae feugiat felis justo vitae magna. Nam tempor hendrerit ligula ac hendrerit. Aliquam erat volutpat. In sed facilisis magna. Mauris et porttitor arcu, eget gravida dolor.\n" +
                "\n" +
                "Mauris a nulla nibh. Cras tristique in ante et lobortis. Ut pretium est metus, nec feugiat massa consectetur eget. Praesent interdum dignissim nunc a efficitur. Nunc malesuada accumsan nibh nec consectetur. Etiam vitae ex dapibus, sodales tortor eu, euismod odio. Nullam commodo blandit elit, pellentesque tristique ipsum cursus eu. Suspendisse eu scelerisque nunc, nec blandit nisl. Suspendisse eleifend condimentum porttitor. Proin efficitur tempor urna, eget volutpat augue ultrices eu. In molestie ipsum cursus ligula commodo pretium. Fusce convallis tellus id libero dapibus scelerisque. Fusce sit amet lorem consectetur, tristique erat eu, blandit neque. Duis nunc est, tincidunt ac feugiat vel, facilisis sit amet sapien.\n" +
                "\n" +
                "Aenean erat tortor, volutpat vel lectus nec, feugiat lobortis dui. Nullam varius mauris eget facilisis lacinia. Phasellus mollis ligula mauris, sit amet auctor nisi consectetur dapibus. Mauris justo diam, vehicula at justo non, placerat tempor diam. Aliquam erat volutpat. Aliquam nec mollis mauris, id ornare libero. Maecenas et dolor ullamcorper, rhoncus dui sed, sollicitudin augue.\n" +
                "\n" +
                "Pellentesque sit amet nisl elementum magna feugiat vestibulum. Aenean dapibus neque facilisis consectetur ornare. Cras tristique eu mauris at ornare. Cras massa est, maximus id fringilla sit amet, vehicula in massa. Sed mi mauris, vestibulum eget mi sit amet, malesuada eleifend massa. Aliquam porta elit ac arcu sodales, at fringilla sem varius. Duis consequat pulvinar est, eget malesuada leo posuere sit amet. Nullam egestas, sem eu dictum mollis, massa tortor pharetra lacus, id rhoncus sapien est ut velit.\n" +
                "\n" +
                "Aliquam viverra sem ac erat pellentesque, non gravida enim dictum. Donec a ornare eros. Nunc aliquet ultrices lectus, quis faucibus eros tempus et. Aliquam condimentum nisi et vehicula sollicitudin. Sed porttitor ligula enim, eget tincidunt eros pulvinar viverra. Aliquam pharetra mauris et elementum tincidunt. Pellentesque rutrum, ante in dictum mattis, lectus magna pellentesque dui, ac porttitor urna neque in dui.\n" +
                "\n" +
                "Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce euismod pharetra mauris et hendrerit. Phasellus purus nunc, fermentum in faucibus sit amet, laoreet sed ipsum. Sed volutpat diam a egestas congue. Donec dapibus laoreet dui sit amet suscipit. Donec ultrices erat congue malesuada ultrices. Ut eleifend orci at condimentum egestas. Nulla rutrum mauris fermentum ex efficitur varius. Etiam vel metus quis est dapibus tempus eu quis leo. Suspendisse sodales massa ac sem facilisis feugiat.\n" +
                "\n" +
                "Duis viverra vestibulum quam, et tristique tellus interdum id. Suspendisse potenti. Nam mattis dui ac lacus tincidunt, at sollicitudin elit vulputate. Vivamus porta ut urna eget imperdiet. Integer elementum fringilla arcu id porta. Curabitur molestie ex eget condimentum blandit. Donec ornare venenatis fringilla. Suspendisse mattis tellus pulvinar, facilisis enim quis, feugiat orci. Mauris augue lacus, sollicitudin sed vulputate ut, hendrerit et arcu. Nam ornare posuere congue. Proin sed tempus arcu, vel suscipit eros. Integer consequat posuere enim vel iaculis. Sed vel sodales magna. Aliquam erat volutpat. Etiam congue pellentesque nibh at eleifend.\n" +
                "\n" +
                "Phasellus lobortis dignissim urna, vel maximus erat bibendum a. Integer mi ligula, efficitur at pretium ut, auctor eget tellus. Ut pharetra, est ut dictum rhoncus, risus ante pellentesque velit, non rutrum est nisl nec neque. Quisque condimentum aliquet enim ac bibendum. Nullam vestibulum felis odio, in pretium odio mattis non. Etiam sed odio ut sem tempor faucibus. Phasellus ultrices nisi a lectus accumsan, vel malesuada velit luctus. Integer pellentesque congue risus, in semper nisl cursus eget. Sed aliquam ipsum felis.\n" +
                "\n" +
                "Pellentesque ultricies ex in posuere ullamcorper. Cras suscipit libero at felis dictum ultrices. In et maximus dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Aenean feugiat velit velit, ut ultrices metus auctor eget. Morbi in leo ante. Duis eget augue sit amet dolor pharetra porta. Ut non ipsum rhoncus est consectetur volutpat. Donec pharetra ultrices felis a venenatis. Nulla placerat consectetur mauris, id congue quam vehicula eget. Etiam accumsan malesuada orci non imperdiet.\n" +
                "\n" +
                "Fusce tincidunt mattis libero, quis lacinia tortor porttitor non. Sed interdum feugiat nisi, ac fermentum lectus rutrum ut. Mauris cursus aliquet volutpat. Pellentesque eu turpis iaculis elit hendrerit laoreet. Vestibulum cursus felis et risus tempus, vitae sagittis diam pellentesque. Vestibulum non tempor leo. Duis pretium felis tortor, sed commodo nisi suscipit sit amet. Nam pharetra, lectus ac tincidunt egestas, diam urna auctor purus, eu pharetra nulla mi et ipsum. Aliquam venenatis eros quis lorem pharetra semper. Sed non tortor diam. Duis egestas, dolor vitae consectetur facilisis, turpis dui rutrum neque, sit amet eleifend elit libero sed turpis. Duis pharetra neque et ipsum porta rhoncus.\n" +
                "\n" +
                "Mauris enim enim, gravida eu egestas sit amet, ultrices eu felis. Etiam semper faucibus dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed eu elit at lectus pretium sodales. Etiam malesuada lorem at tincidunt aliquet. Mauris in orci a leo sollicitudin auctor sit amet vitae felis.\n" +
                "\n" +
                "Nullam sit amet imperdiet ipsum, pharetra facilisis risus. Pellentesque sem felis, bibendum vel lacus id, mattis elementum velit. Sed eu ullamcorper nibh. Nunc pharetra augue molestie dui posuere pellentesque. Suspendisse maximus nunc vitae congue commodo. In hac habitasse platea dictumst. Nulla tempus fermentum mi, a fringilla magna gravida vel. Quisque a augue non tortor lobortis faucibus ut eu ligula. Fusce ullamcorper, magna ut mattis vestibulum, nunc urna mollis lorem, eget dapibus nibh arcu ut erat. Proin convallis rhoncus purus a mattis. Nulla mattis vel felis ut iaculis. Integer congue, massa ac faucibus volutpat, ante ipsum elementum diam, at porta diam quam non velit. Nunc at elementum neque, ut congue ipsum. In blandit tincidunt pellentesque. Fusce non enim eu tortor ultricies sagittis. Ut elementum eros sed lorem posuere egestas.");

        postList.add(post1);
        postList.add(post2);

        for (Post p:
             postList) {
            codeBlogRepository.save(p);
            System.out.println(p.getId());
        }
    }
}
